# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "bastion" do |vm1|
    #vm1.vm.box = "centos/8"
    vm1.vm.box = "almalinux/8"
    vm1.vm.hostname = 'bastion'
    vm1.vm.network "forwarded_port", id: "ssh", host: 1337, guest: 22
    vm1.vm.network "forwarded_port", id: "meshcmd", host: 3000, guest: 3000
    vm1.vm.network "public_network", bridge: [
      "en8: Dell Universal Dock D6000",
      "en0: Wi-Fi (AirPort)",    
    ]

    config.vm.provider "virtualbox" do |v, override|
      v.customize ["modifyvm", :id, "--usbxhci", "on"]
      v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      # add cdrom
      v.customize ["storageattach", :id,
                "--storagectl", "IDE Controller",
                "--port", "0", "--device", "1",
                "--type", "dvddrive",
                "--medium", "emptydrive"]
      v.memory = "4096"
      v.cpus = 2
    end

  config.vm.provision "shell", privileged: true, path: "rhel_init.sh"
  config.vm.provision "shell", privileged: true, path: "rhel_init.sh"

  config.vm.provision "shell", privileged: true, path: "podman_init.sh"
  config.vm.provision "shell", privileged: false, path: "podman_user.sh"

  config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"

  end
end
